export const ActionTypes = {
  MOVİES_LOADING: "LOADING",
  MOVİES_SUCCESS: "SUCCESS",
  MOVİES_ERROR: "ERROR",
  GENRES_LOADING: "GENRES_LOADING",
  GENRES_SUCCESS: "GENRES_SUCCESS",
  GENRES_ERROR: "GENRES_ERROR",
};
